channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annexremote=1.5.0
  - appdirs=1.4.4
  - boto=2.49.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.9
  - colorama=0.4.4
  - cryptography=35.0.0
  - curl=7.78.0
  - datalad=0.15.3
  - dbus=1.13.6
  - deprecated=1.2.13
  - distro=1.6.0
  - exifread=2.3.2
  - expat=2.2.10
  - fasteners=0.16
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - git=2.32.0
  - git-annex=8.20211123
  - glib=2.69.1
  - humanize=3.13.1
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_metadata=4.10.0
  - iso8601=1.0.2
  - jeepney=0.7.1
  - jpeg=9d
  - keyring=23.4.0
  - keyrings.alt=4.0.2
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - libcurl=7.78.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.0.10
  - lz4-c=1.9.3
  - monotonic=1.5
  - msgpack-python=1.0.2
  - mutagen=1.45.1
  - ncurses=6.3
  - olefile=0.46
  - openssl=1.1.1l
  - p7zip=16.02
  - patool=1.12
  - pcre=8.45
  - pcre2=10.35
  - perl=5.32.1
  - pillow=6.2.1
  - pip=21.2.4
  - psutil=5.8.0
  - pycparser=2.21
  - pygithub=1.55
  - pyjwt=2.3.0
  - pynacl=1.4.0
  - pyopenssl=21.0.0
  - pyperclip=1.8.2
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-gitlab=2.10.1
  - python_abi=3.8
  - pyyaml=6.0
  - readline=8.1
  - requests=2.26.0
  - requests-ftp=0.3.1
  - requests-toolbelt=0.9.1
  - secretstorage=3.3.1
  - setuptools=58.0.4
  - simplejson=3.17.6
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tqdm=4.62.3
  - urllib3=1.26.7
  - wheel=0.37.0
  - whoosh=2.7.4
  - wrapt=1.12.1
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - backcall==0.2.0
      - datalad-container==1.1.5
      - debugpy==1.5.1
      - decorator==5.1.0
      - entrypoints==0.3
      - ipykernel==6.6.0
      - ipython==7.30.1
      - jedi==0.18.1
      - jupyter-client==7.1.0
      - jupyter-core==4.9.1
      - matplotlib-inline==0.1.3
      - nest-asyncio==1.5.4
      - numpy==1.21.5
      - pandas==1.3.5
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.24
      - ptyprocess==0.7.0
      - pygments==2.10.0
      - pyocclient==0.6
      - pytz==2021.3
      - pyzmq==22.3.0
      - simple-slurm==0.2.2
      - tornado==6.1
      - traitlets==5.1.1
      - wcwidth==0.2.5
